#ifndef SPACE_PACKET_H
#define SPACE_PACKET_H

#define SPACE_PACKET_PRIMARY_HEADER_SIZE_BYTES 6
#define SPACE_PACKET_ERROR_CONTROL_SIZE_BYTES 2
#define SPACE_PACKET_MAX_PACKET_DATA_SIZE 65536      // 2^16
#define SPACE_PACKET_MAX_PACKET_SEQUENCE_COUNT 16383 // 2^14-1
#define SPACE_PACKET_MAX_APID_SIZE 2047              // 2^11-1

#define SPACE_PACKET_VERSION_NUMBER_MASK 0x07
#define SPACE_PACKET_TYPE_MASK 0x08
#define SPACE_PACKET_APID_HIGH_BITS_MASK 0xE0
#define SPACE_PACKET_SECONDARY_HEADER_FLAG_MASK 0x16
#define SPACE_PACKET_SEQUENCE_FLAGS_FIRST_MASK 0x01
#define SPACE_PACKET_SEQUENCE_FLAGS_SECOND_MASK 0x02

#define SPACE_PACKET_VERSION_NUMBER_OFFSET 0u
#define SPACE_PACKET_TYPE_OFFSET 3u
#define SPACE_PACKET_APID_HIGH_BITS_OFFSET 5u
#define SPACE_PACKET_SECONDARY_HEADER_FLAG_OFFSET 4u
#define SPACE_PACKET_SEQUENCE_FLAGS_FIRST_OFFSET 0u
#define SPACE_PACKET_SEQUENCE_FLAGS_SECOND_OFFSET 1u
#define SPACE_PACKET_SEQUENCE_CONTROL_HIGH_BITS_OFFSET 2u

#endif // SPACE_PACKET_H
