#ifndef SPACE_PACKET_H
#define SPACE_PACKET_H

#define SPACE_PACKET_PRIMARY_HEADER_SIZE_BYTES 6
#define SPACE_PACKET_ERROR_CONTROL_SIZE_BYTES 2
#define SPACE_PACKET_MAX_PACKET_DATA_SIZE 65536      // 2^16
#define SPACE_PACKET_MAX_PACKET_SEQUENCE_COUNT 16383 // 2^14-1
#define SPACE_PACKET_MAX_APID_SIZE 2047              // 2^11-1

#endif // SPACE_PACKET_H
