/* Body file for function TimeService
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/

#include "timeservice-api.h"
#include "timeservice.h"

static TimeService time_service;

void timeservice_startup(void)
{
   TimeService_Startup(&time_service);
}

void timeservice_PI_CfsTimestampCmp(const asn1SccCfsTimestamp *t1, const asn1SccCfsTimestamp *t2, asn1SccComparisonResult *result)
{
   *result = TimeService_CfsTimestampCmp(&time_service, t1, t2);
}

void timeservice_PI_ClockStatus(asn1SccClockStatusEnum *status)
{
   *status = TimeService_ClockStatus(&time_service);
}

void timeservice_PI_CucTimestampCmp(const asn1SccCucTimestamp *t1, const asn1SccCucTimestamp *t2, asn1SccComparisonResult *result)
{
   *result = TimeService_CucTimestampCmp(&time_service, t1, t2);
}

void timeservice_PI_ObetTime(asn1SccULongInteger *nanoseconds)
{
   *nanoseconds = TimeService_ObetTime(&time_service);
}

void timeservice_PI_CucTimestamp(const asn1SccULongInteger *nanoseconds, asn1SccCucTimestamp *timestamp)
{
   TimeService_CucTimestamp(&time_service, *nanoseconds, timestamp);
}
