name: Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install development tools
        run: sudo apt install -y clang-tidy

      - name: Run CMake
        run: cmake -S . -B build/ -DCMAKE_BUILD_TYPE=Debug -DTOOLS_ENABLE_TIDY=ON -DTASTE_RUNTIME_COMMON_BUILD_TESTS=ON -DTASTE_RUNTIME_COMMON_WARNINGS_AS_ERRORS=ON

      - name: Build
        run: cmake --build build/

      - name: Run tests
        run: ctest --test-dir build/ -V --output-on-failure
